version: '3.4'

services:
   ghiro-mariadb:
      image: mariadb
      hostname: ghiro-mariadb
      container_name: ghiro-mariadb
      environment:
         MYSQL_ROOT_PASSWORD: ghiromanager
         MYSQL_USER: ghiro
         MYSQL_PASSWORD: ghiromanager
         MYSQL_DATABASE: ghiro
      volumes:
         - $PWD/db:/var/lib/mysql
      ports:
         - 3306:3306
      restart: always

   ghiro-mongodb:
      image: mongo:latest
      hostname: ghiro-mongodb
      container_name: ghiro-mongodb
      ports:
         - 27017:27017
      restart: always
